name: Test LolSapiens

on:
  push:
    branches:
      - main
      - feature/*

# env:
#   APP_NAME: <Your app name>

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint backend code
      run: |
        black .

    - name: Test backend
      run: |
        pytest -v

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    # - name: Lint frontend code
    #   run: |
    #     cd frontend
    #     npm run lint

    # - name: Build and test frontend
    #   run: |
    #     cd frontend
    #     npm run build
    #     npm test