name: Test LolSapiens

on:
  push:
    branches:
      - main
      - feature/*

# env:
#   APP_NAME: <Your app name>

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint backend code
      run: |
        black .

    - name: Test backend
      run: |
        pytest -v

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    # - name: Lint frontend code
    #   run: |
    #     cd frontend
    #     npm run lint

    # - name: Build and test frontend
    #   run: |
    #     cd frontend
    #     npm run build
    #     npm test