name: Test LolSapiens

on:
  push:
    branches:
      - main

# env:
#   APP_NAME: <Your app name>

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        node-version: [14.x, 16.x]
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint backend code
        run: |
          black backend/

      - name: Test backend
        run: |
          pytest -vv

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

    # - name: Lint frontend code
    #   run: |
    #     cd frontend
    #     npm run lint

    # - name: Build and test frontend
    #   run: |
    #     cd frontend
    #     npm run build
    #     npm test


